### ISSUE TITLE
Meeting on Monday

### ISSUE THREAD

**Issue by changsiyao** [berkeley-stat159/project-theta#65] opened 2015-11-20 08:50 UTC
We set up a meeting with Jarrod on Monday (11/23) 3-4 PM in the third floor lounge we normally meet.
@jarrodmillman @BenjaminHsieh @pigriver123 @boyinggong @brianqiu

**Comment by boyinggong** [comment] 2015-11-21 22:31
Questions:
1. Should we use the standard brain datasets or the original datasets? Can we map the coefficient calculated from the original datasets to the standard brain rather than do mapping first and then do the regression?
2. If we fit regression models for each run, the percentage of significant coefficient value is approximately 80%. However, if we combine the 3 runs for each subject together, the percentage falls drastically to 20%. Can we fit regression models for each run rather than for each subject?
3. How to delete outliers? Some runs have lots of outliers.
4. Should we fit the model using linear drift and quadratic drift?

**Comment by briankleinqiu** [comment] 2015-11-21 22:43
To add onto 4 we should clarify if we need to do drift for the new standard brain datasets since I think Matthew already said we should do it for the original.
1. Spatial smoothing vs. temporal smoothing - differences, and how to implement spatial smoothing (is it the same as lecture examples or gaussian_filter in scipy.nd.image.filters)

**Comment by briankleinqiu** [comment] 2015-11-23 01:47
Instead of the smoothing question above, can you instead ask for me if we should smooth before or after the analyses (i'm pretty sure after but just to be 100% clear)

**Comment by BenjaminHsieh** [comment] 2015-11-23 10:00
Brian can you clarify what portion of the anlyses you mean? 

Also to ask: 
- how to write test functions for plots? Do we just manually check that they are close?
- path error to nosetest for test functions that calls for a data file in our data directory, cannot find the file if we run make test from the main project repository

**Comment by changsiyao** [comment] 2015-11-24 00:01
Need to do smoothing before modeling.
Maybe should do separate runs instead of combining runs of a subject.
Add linear/quadratic drift.
Need to move python scripts into a script directory. Can also make a new plotting directory.

**Comment by BenjaminHsieh** [comment] 2015-11-24 17:57
p-values: may try rank cutoff (take the head of maximums)
Signal may be easier to see with motion-corrected, but distrust it. 
Outliers: can choose to analyze with and without them: also can look at other criterion eg artifacts by SD, VAR plot over time by, and intensity vs time graph

**Comment by BenjaminHsieh** [comment] 2015-12-15 05:10
closing

**Closed as completed by BenjaminHsieh** 2015-12-15 05:10 UTC
